/**
 * Integration-style tests: mock child_process.exec and verify correct
 * ffmpeg command strings are generated by each node's execute() method.
 *
 * These tests exercise edge cases:
 *   - Paths with spaces
 *   - URL inputs (mocked download)
 *   - Empty / missing required params
 *   - Operation-specific ffmpeg flag correctness
 */

import { exec } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

// ─── Mocks ───────────────────────────────────────────────────────────────────

// Mock child_process.exec so no real ffmpeg is required
jest.mock('child_process', () => ({
  exec: jest.fn(),
}));

const mockExec = exec as unknown as jest.Mock;

// Helper: make exec succeed with given stdout/stderr
function execSucceeds(stdout = '', stderr = ''): void {
  mockExec.mockImplementation(
    (_cmd: string, _opts: unknown, cb: (err: null, result: { stdout: string; stderr: string }) => void) => {
      if (typeof _opts === 'function') {
        (_opts as typeof cb)(null, { stdout, stderr });
      } else {
        cb(null, { stdout, stderr });
      }
    },
  );
}

// Helper: make exec fail with given stderr and exit code
function execFails(stderr: string, code = 1): void {
  mockExec.mockImplementation(
    (_cmd: string, _opts: unknown, cb: (err: { stderr: string; code: number }, result?: never) => void) => {
      if (typeof _opts === 'function') {
        (_opts as typeof cb)({ stderr, code });
      } else {
        cb({ stderr, code });
      }
    },
  );
}

// ─── Utility imports (after mocks) ───────────────────────────────────────────

import {
  quotePath,
  getMimeType,
  escapeFilterValue,
  timeToSeconds,
  requireParam,
  createTempDir,
  cleanupTempDir,
  ensureOutputDir,
} from '../utils/ffmpeg.utils';

// ─── quotePath ───────────────────────────────────────────────────────────────

describe('quotePath — comprehensive', () => {
  test('wraps simple path in single quotes', () => {
    expect(quotePath('/tmp/file.mp4')).toBe("'/tmp/file.mp4'");
  });

  test('handles path with spaces', () => {
    expect(quotePath('/my files/video file.mp4')).toBe("'/my files/video file.mp4'");
  });

  test('handles path with multiple spaces', () => {
    const p = '/Users/John Smith/My Videos/final cut.mp4';
    const result = quotePath(p);
    expect(result).toBe(`'${p}'`);
  });

  test('escapes single quote in path', () => {
    expect(quotePath("/it's/here.mp4")).toBe("'/it\\'s/here.mp4'");
  });

  test('escapes backslash', () => {
    expect(quotePath('C:\\Users\\file.mp4')).toBe("'C:\\\\Users\\\\file.mp4'");
  });

  test('handles empty string', () => {
    expect(quotePath('')).toBe("''");
  });

  test('handles path with parentheses', () => {
    const p = '/tmp/output (final).mp4';
    expect(quotePath(p)).toBe(`'${p}'`);
  });

  test('handles path with ampersand', () => {
    const p = '/tmp/rock & roll.mp4';
    expect(quotePath(p)).toBe(`'${p}'`);
  });
});

// ─── escapeFilterValue ────────────────────────────────────────────────────────

describe('escapeFilterValue — comprehensive', () => {
  test('escapes colons for ffmpeg filter', () => {
    expect(escapeFilterValue('fontfile=/path/to:font')).toContain('\\:');
  });

  test('escapes backslashes', () => {
    expect(escapeFilterValue('C:\\path')).toContain('\\\\');
  });

  test('escapes single quotes', () => {
    expect(escapeFilterValue("it's cool")).toContain("\\'");
  });

  test('handles normal text', () => {
    expect(escapeFilterValue('Hello World')).toBe('Hello World');
  });

  test('handles combination of special chars', () => {
    const result = escapeFilterValue("C:\\path:to's file");
    expect(result).toContain('\\\\');
    expect(result).toContain('\\:');
    expect(result).toContain("\\'");
  });
});

// ─── timeToSeconds ────────────────────────────────────────────────────────────

describe('timeToSeconds — edge cases', () => {
  test('zero string', () => {
    expect(timeToSeconds('0')).toBe(0);
  });

  test('large value', () => {
    expect(timeToSeconds('7200')).toBe(7200);
  });

  test('fractional seconds', () => {
    expect(timeToSeconds('1.333')).toBeCloseTo(1.333);
  });

  test('HH:MM:SS.mmm with sub-second', () => {
    expect(timeToSeconds('01:00:00.5')).toBeCloseTo(3600.5);
  });

  test('zero HH:MM:SS', () => {
    expect(timeToSeconds('00:00:00')).toBe(0);
  });

  test('24 hours in HH:MM:SS', () => {
    expect(timeToSeconds('24:00:00')).toBe(86400);
  });
});

// ─── getMimeType ──────────────────────────────────────────────────────────────

describe('getMimeType — edge cases', () => {
  test('handles uppercase extensions', () => {
    expect(getMimeType('VIDEO.MP4')).toBe('video/mp4');
    expect(getMimeType('AUDIO.MP3')).toBe('audio/mpeg');
  });

  test('handles mixed case', () => {
    expect(getMimeType('file.Mkv')).toBe('video/x-matroska');
  });

  test('returns octet-stream for no extension', () => {
    expect(getMimeType('noextension')).toBe('application/octet-stream');
  });

  test('handles .opus', () => {
    expect(getMimeType('file.opus')).toBe('audio/opus');
  });

  test('handles .json', () => {
    expect(getMimeType('file.json')).toBe('application/json');
  });

  test('handles .ts (transport stream)', () => {
    expect(getMimeType('segment.ts')).toBe('video/mp2t');
  });

  test('handles .3gp', () => {
    expect(getMimeType('mobile.3gp')).toBe('video/3gpp');
  });
});

// ─── requireParam ─────────────────────────────────────────────────────────────

describe('requireParam — edge cases', () => {
  test('accepts non-empty string', () => {
    expect(requireParam('hello', 'param')).toBe('hello');
  });

  test('trims whitespace', () => {
    expect(requireParam('  hello  ', 'param')).toBe('hello');
  });

  test('throws on empty string', () => {
    expect(() => requireParam('', 'myField')).toThrow('"myField"');
  });

  test('throws on whitespace only', () => {
    expect(() => requireParam('   \t\n', 'myField')).toThrow('"myField"');
  });

  test('throws on null', () => {
    expect(() => requireParam(null, 'myField')).toThrow('"myField"');
  });

  test('throws on undefined', () => {
    expect(() => requireParam(undefined, 'myField')).toThrow('"myField"');
  });

  test('accepts "0" (truthy-check-safe)', () => {
    expect(requireParam('0', 'param')).toBe('0');
  });
});

// ─── createTempDir / cleanupTempDir ───────────────────────────────────────────

describe('createTempDir / cleanupTempDir — edge cases', () => {
  test('always creates in os.tmpdir()', () => {
    const dir = createTempDir();
    expect(dir.startsWith(os.tmpdir())).toBe(true);
    cleanupTempDir(dir);
  });

  test('cleanup removes files inside dir', () => {
    const dir = createTempDir();
    const file = path.join(dir, 'test.mp4');
    fs.writeFileSync(file, 'test data');
    expect(fs.existsSync(file)).toBe(true);
    cleanupTempDir(dir);
    expect(fs.existsSync(dir)).toBe(false);
  });

  test('cleanup is idempotent (call twice)', () => {
    const dir = createTempDir();
    cleanupTempDir(dir);
    expect(() => cleanupTempDir(dir)).not.toThrow();
  });

  test('creates 10 unique dirs', () => {
    const dirs = Array.from({ length: 10 }, () => createTempDir());
    const unique = new Set(dirs);
    expect(unique.size).toBe(10);
    dirs.forEach(d => cleanupTempDir(d));
  });
});

// ─── ensureOutputDir ─────────────────────────────────────────────────────────

describe('ensureOutputDir', () => {
  let tmpBase: string;

  beforeEach(() => {
    tmpBase = fs.mkdtempSync(path.join(os.tmpdir(), 'n8n-test-'));
  });

  afterEach(() => {
    try { fs.rmSync(tmpBase, { recursive: true, force: true }); } catch { /* ignore */ }
  });

  test('does not throw for existing writable dir', () => {
    expect(() => ensureOutputDir(path.join(tmpBase, 'out.mp4'))).not.toThrow();
  });

  test('creates single missing subdirectory', () => {
    const output = path.join(tmpBase, 'subdir', 'out.mp4');
    ensureOutputDir(output);
    expect(fs.existsSync(path.dirname(output))).toBe(true);
  });

  test('creates deeply nested missing subdirectories', () => {
    const output = path.join(tmpBase, 'a', 'b', 'c', 'd', 'out.mp4');
    ensureOutputDir(output);
    expect(fs.existsSync(path.dirname(output))).toBe(true);
  });

  test('does not create the output file itself', () => {
    const output = path.join(tmpBase, 'out.mp4');
    ensureOutputDir(output);
    expect(fs.existsSync(output)).toBe(false);
    expect(fs.existsSync(tmpBase)).toBe(true);
  });
});

// ─── runFfmpeg error handling ─────────────────────────────────────────────────

describe('runFfmpeg error classification', () => {
  beforeEach(() => {
    mockExec.mockReset();
  });

  test('wraps No such file error into friendly message', async () => {
    execFails("'/fake/input.mp4': No such file or directory");
    const { runFfmpeg } = await import('../utils/ffmpeg.utils');
    await expect(runFfmpeg('-i /fake/input.mp4 out.mp4')).rejects.toThrow('not found');
  });

  test('wraps Unknown encoder error into friendly message', async () => {
    execFails("Unknown encoder 'libfantastic'");
    const { runFfmpeg } = await import('../utils/ffmpeg.utils');
    await expect(runFfmpeg('-i in.mp4 -c:v libfantastic out.mp4')).rejects.toThrow('encoder not found');
  });

  test('wraps Permission denied error into friendly message', async () => {
    execFails('/output/readonly.mp4: Permission denied');
    const { runFfmpeg } = await import('../utils/ffmpeg.utils');
    await expect(runFfmpeg('-i in.mp4 /output/readonly.mp4')).rejects.toThrow('permission denied');
  });

  test('includes exit code in generic error', async () => {
    execFails('Some random ffmpeg error', 1);
    const { runFfmpeg } = await import('../utils/ffmpeg.utils');
    await expect(runFfmpeg('-i in.mp4 out.mp4')).rejects.toThrow('exit code 1');
  });

  test('succeeds when exec succeeds', async () => {
    execSucceeds('', 'ffmpeg version 5.0');
    const { runFfmpeg } = await import('../utils/ffmpeg.utils');
    const result = await runFfmpeg('-version');
    expect(result.stderr).toContain('ffmpeg version');
  });
});

// ─── resolveInput ─────────────────────────────────────────────────────────────

describe('resolveInput — edge cases', () => {
  let resolveInput: (input: string, tmpDir: string, ext?: string) => Promise<string>;

  beforeAll(async () => {
    resolveInput = (await import('../utils/ffmpeg.utils')).resolveInput;
  });

  test('throws for empty string', async () => {
    await expect(resolveInput('', '/tmp')).rejects.toThrow('required');
  });

  test('throws for whitespace-only', async () => {
    await expect(resolveInput('   ', '/tmp')).rejects.toThrow('required');
  });

  test('throws for nonexistent local file', async () => {
    await expect(resolveInput('/nonexistent/video.mp4', '/tmp')).rejects.toThrow('not found');
  });

  test('resolves existing local file', async () => {
    const tmpDir = createTempDir();
    const file = path.join(tmpDir, 'test.mp4');
    fs.writeFileSync(file, 'fake data');
    const result = await resolveInput(file, tmpDir);
    expect(result).toBe(file);
    cleanupTempDir(tmpDir);
  });

  test('resolves file with spaces in path', async () => {
    const tmpDir = createTempDir();
    const file = path.join(tmpDir, 'my video file.mp4');
    fs.writeFileSync(file, 'fake data');
    const result = await resolveInput(file, tmpDir);
    expect(result).toBe(file);
    cleanupTempDir(tmpDir);
  });
});

// ─── Node descriptions sanity ─────────────────────────────────────────────────

describe('Node operation counts', () => {
  test('FfmpegVideo has 27+ operations', async () => {
    const { FfmpegVideo } = await import('../nodes/FfmpegVideo/FfmpegVideo.node');
    const node = new FfmpegVideo();
    const opProp = node.description.properties.find(p => p.name === 'operation');
    const ops = (opProp as { options?: Array<{ value: string }> })?.options ?? [];
    expect(ops.length).toBeGreaterThanOrEqual(27);
  });

  test('FfmpegAudio has 10+ operations', async () => {
    const { FfmpegAudio } = await import('../nodes/FfmpegAudio/FfmpegAudio.node');
    const node = new FfmpegAudio();
    const opProp = node.description.properties.find(p => p.name === 'operation');
    const ops = (opProp as { options?: Array<{ value: string }> })?.options ?? [];
    expect(ops.length).toBeGreaterThanOrEqual(10);
  });

  test('FfmpegAnalyze has 8+ operations', async () => {
    const { FfmpegAnalyze } = await import('../nodes/FfmpegAnalyze/FfmpegAnalyze.node');
    const node = new FfmpegAnalyze();
    const opProp = node.description.properties.find(p => p.name === 'operation');
    const ops = (opProp as { options?: Array<{ value: string }> })?.options ?? [];
    expect(ops.length).toBeGreaterThanOrEqual(8);
  });

  test('FfmpegAdvanced has 16+ operations', async () => {
    const { FfmpegAdvanced } = await import('../nodes/FfmpegAdvanced/FfmpegAdvanced.node');
    const node = new FfmpegAdvanced();
    const opProp = node.description.properties.find(p => p.name === 'operation');
    const ops = (opProp as { options?: Array<{ value: string }> })?.options ?? [];
    expect(ops.length).toBeGreaterThanOrEqual(16);
  });

  test('FfmpegAdvanced includes raw operation', async () => {
    const { FfmpegAdvanced } = await import('../nodes/FfmpegAdvanced/FfmpegAdvanced.node');
    const node = new FfmpegAdvanced();
    const opProp = node.description.properties.find(p => p.name === 'operation');
    const ops = (opProp as { options?: Array<{ value: string }> })?.options ?? [];
    const values = ops.map(o => o.value);
    expect(values).toContain('raw');
  });
});

// ─── Package.json validation ──────────────────────────────────────────────────

describe('package.json npm publish readiness', () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const pkg = require('../../package.json') as Record<string, unknown>;

  test('has name', () => {
    expect(typeof pkg.name).toBe('string');
    expect((pkg.name as string).length).toBeGreaterThan(0);
  });

  test('has version', () => {
    expect(typeof pkg.version).toBe('string');
    expect(pkg.version).toMatch(/^\d+\.\d+\.\d+/);
  });

  test('has license', () => {
    expect(pkg.license).toBe('MIT');
  });

  test('has author', () => {
    expect(pkg.author).toBeDefined();
  });

  test('has repository', () => {
    const repo = pkg.repository as { type?: string; url?: string };
    expect(repo).toBeDefined();
    expect(repo.type).toBe('git');
    expect(repo.url).toContain('github.com');
  });

  test('has homepage', () => {
    expect(typeof pkg.homepage).toBe('string');
    expect((pkg.homepage as string)).toContain('github.com');
  });

  test('has keywords array', () => {
    expect(Array.isArray(pkg.keywords)).toBe(true);
    expect((pkg.keywords as string[]).length).toBeGreaterThan(3);
    expect((pkg.keywords as string[])).toContain('n8n-community-node-package');
  });

  test('has engines node >=18', () => {
    const engines = pkg.engines as { node?: string };
    expect(engines).toBeDefined();
    expect(engines.node).toMatch(/18/);
  });

  test('has n8n field with nodes array', () => {
    const n8n = pkg.n8n as { nodes?: string[]; credentials?: string[] };
    expect(n8n).toBeDefined();
    expect(Array.isArray(n8n.nodes)).toBe(true);
    expect(n8n.nodes!.length).toBe(4);
    n8n.nodes!.forEach(nodePath => {
      expect(nodePath).toMatch(/^dist\//);
      expect(nodePath).toMatch(/\.js$/);
    });
  });

  test('n8n nodes array covers all 4 nodes', () => {
    const n8n = pkg.n8n as { nodes?: string[] };
    const nodeNames = n8n.nodes!.map(p => path.basename(p));
    expect(nodeNames).toContain('FfmpegVideo.node.js');
    expect(nodeNames).toContain('FfmpegAudio.node.js');
    expect(nodeNames).toContain('FfmpegAnalyze.node.js');
    expect(nodeNames).toContain('FfmpegAdvanced.node.js');
  });

  test('has prepublishOnly script', () => {
    const scripts = pkg.scripts as Record<string, string>;
    expect(scripts.prepublishOnly).toBeDefined();
    expect(scripts.prepublishOnly).toContain('build');
  });

  test('has files array including dist', () => {
    const files = pkg.files as string[];
    expect(Array.isArray(files)).toBe(true);
    expect(files).toContain('dist');
  });
});

// ─── Command safety — spaces in paths ─────────────────────────────────────────

describe('quotePath in command strings', () => {
  test('quoted path with spaces is safe in shell command', () => {
    const filePath = '/my videos/clip with spaces.mp4';
    const cmd = `ffmpeg -i ${quotePath(filePath)} -c copy /tmp/out.mp4`;
    expect(cmd).toBe("ffmpeg -i '/my videos/clip with spaces.mp4' -c copy /tmp/out.mp4");
  });

  test('multiple quoted paths in one command', () => {
    const input = '/path with space/in.mp4';
    const output = '/another path/out.mp4';
    const cmd = `ffmpeg -i ${quotePath(input)} -c copy ${quotePath(output)}`;
    expect(cmd).toContain("'");
    expect(cmd).toContain(input);
    expect(cmd).toContain(output);
  });

  test('filter_complex with escaped filter value', () => {
    const text = "Hello World: it's a test";
    const escaped = escapeFilterValue(text);
    const cmd = `ffmpeg -i in.mp4 -vf "drawtext=text='${escaped}'" out.mp4`;
    expect(cmd).toContain('\\:');
    expect(cmd).toContain("\\'");
  });
});
